M48
; DRILL file {KiCad (6.0.2)} date Sun May  1 12:50:57 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-01T12:50:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1181
%
G90
G05
T1
X7.5304Y-3.7765
X7.5894Y-3.5949
T2
X6.7433Y-4.7693
T3
X7.6402Y-3.8246
X7.7065Y-3.6206
T4
X6.0602Y-2.2575
X6.0602Y-4.4425
T0
M30
